name: Build DataScan EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependências
        run: |
          pip install pyinstaller
          pip install flask pandas openpyxl pywebview

      - name: Gerar Executável
        run: |
          pyinstaller --onefile --noconsole ^
            --hidden-import=webview ^
            --add-data "templates;templates" ^
            --add-data "static;static" ^
            app.py

      - name: Salvar Executável
        uses: actions/upload-artifact@v4
        with:
          name: DataScan-EXE
          path: dist/app.exe
